//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AupLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AupLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon AupFile {
            get {
                object obj = ResourceManager.GetObject("AupFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   DefaultProfileDisplayName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultProfileDisplayName {
            get {
                return ResourceManager.GetString("DefaultProfileDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EK_Audacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EK_Audacity {
            get {
                return ResourceManager.GetString("EK_Audacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EK_AviUtl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EK_AviUtl {
            get {
                return ResourceManager.GetString("EK_AviUtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EK_InvalidValue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EK_InvalidValue {
            get {
                return ResourceManager.GetString("EK_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EK_Nothing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EK_Nothing {
            get {
                return ResourceManager.GetString("EK_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EK_RunCustomProgram に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EK_RunCustomProgram {
            get {
                return ResourceManager.GetString("EK_RunCustomProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EK_ShowError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EK_ShowError {
            get {
                return ResourceManager.GetString("EK_ShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line1 {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line1 {
            get {
                return ResourceManager.GetString("ER_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line2 {
            get {
                return ResourceManager.GetString("ER_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line3 {
            get {
                return ResourceManager.GetString("ER_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line4 {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line4 {
            get {
                return ResourceManager.GetString("ER_Line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line5 {0:yyyyMMddHHmmssfff} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line5 {
            get {
                return ResourceManager.GetString("ER_Line5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line6 {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line6 {
            get {
                return ResourceManager.GetString("ER_Line6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line7 {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line7 {
            get {
                return ResourceManager.GetString("ER_Line7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line8_Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line8_Data {
            get {
                return ResourceManager.GetString("ER_Line8_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line8_HelpLink {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line8_HelpLink {
            get {
                return ResourceManager.GetString("ER_Line8_HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line8_HResult {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line8_HResult {
            get {
                return ResourceManager.GetString("ER_Line8_HResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line8_Message {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line8_Message {
            get {
                return ResourceManager.GetString("ER_Line8_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line8_Source {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line8_Source {
            get {
                return ResourceManager.GetString("ER_Line8_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line8_SourceFunc {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line8_SourceFunc {
            get {
                return ResourceManager.GetString("ER_Line8_SourceFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line8_StackTrace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line8_StackTrace {
            get {
                return ResourceManager.GetString("ER_Line8_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ER_Line8_Title {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ER_Line8_Title {
            get {
                return ResourceManager.GetString("ER_Line8_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message_ConfirmUninstalling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_ConfirmUninstalling {
            get {
                return ResourceManager.GetString("Message_ConfirmUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message_ErrorReport {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_ErrorReport {
            get {
                return ResourceManager.GetString("Message_ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message_FileNotFound {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_FileNotFound {
            get {
                return ResourceManager.GetString("Message_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message_InvalidExecutionKind に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_InvalidExecutionKind {
            get {
                return ResourceManager.GetString("Message_InvalidExecutionKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message_InvalidType {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_InvalidType {
            get {
                return ResourceManager.GetString("Message_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NewProfileDisplayName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewProfileDisplayName {
            get {
                return ResourceManager.GetString("NewProfileDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShellDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellDescription {
            get {
                return ResourceManager.GetString("ShellDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShellMenu_Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellMenu_Open {
            get {
                return ResourceManager.GetString("ShellMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI_aud_path_filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UI_aud_path_filter {
            get {
                return ResourceManager.GetString("UI_aud_path_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI_avi_path_filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UI_avi_path_filter {
            get {
                return ResourceManager.GetString("UI_avi_path_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI_cus_path_filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UI_cus_path_filter {
            get {
                return ResourceManager.GetString("UI_cus_path_filter", resourceCulture);
            }
        }
    }
}
